### ISSUE TITLE
ImportError: cannot import name 'Trainer' from 'ray.train.trainer'

### ISSUE THREAD

**Issue by Ekansh-Mittal1** [ludwig-ai/ludwig#2876]
I am trying to use create_auto_config from ludwig.automl. Importing create_auto_config leads to the error detailed below. 

Code: `from ludwig.automl import create_auto_config`
Error: `ImportError: cannot import name 'Trainer' from 'ray.train.trainer' (C:\Users\emwt2\Desktop\SF22-23-OHSU\ISPY-analysis\venv\lib\site-packages\ray\train\trainer.py`

![Screenshot_2022-12-22_142332](https://user-images.githubusercontent.com/69400614/209239086-53be9b31-c236-4fde-a46d-3e9d43c558f4.png)

I looked at the file listed in the error, and the "Trainer" class does not exist there. 

- OS: Windows 10
- Version: 10.0.19044
- Python version: 3.9.10
- Ludwig version: 0.6.4
- ray version: 2.2.0

What can I do to resolve this? Thanks in advance.

**Comment by tgaddair** [comment]
Hi @Ekansh-Mittal1, sorry for the confusion on this. At the moment, Ludwig only support Ray 2.0. We are working on upgrading to 2.1 and 2.2 in #2709.

Are you able to downgrade to 2.0 temporarily? If not, we should have this PR landed very soon.

cc @geoffreyangus @arnavgarg1

**Comment by Ekansh-Mittal1** [comment]
yes, I downgraded and the error was resolved. Thank you so much for your
help.
